/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasamortizacionvistagui;

import control.Controlador;
import datos.DatosDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Aguilar Quesada
 */
public class InputForm extends javax.swing.JFrame {

    /**
     * Creates new form InputForm
     */
    public InputForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entradaDeudaInicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        entradaPlazo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entradaTasaAnual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        entradaSistemaAmortizacion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        entradaTipoMoneda = new javax.swing.JComboBox<>();
        botonCalcularAmortizacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculador de Amortizaciones");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(0, 0, 650, 500));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("Calculador de Amortizaciones");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("Nombre del Cliente");

        entradaNombreCliente.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 0));
        jLabel3.setText("Monto solicitado");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 0));
        jLabel4.setText("Plazo (en años)");

        entradaPlazo.setToolTipText("Debe ser un número entero");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 0));
        jLabel5.setText("Tasa Interés Anual");

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 0));
        jLabel6.setText("Sistema de Amortización");

        entradaSistemaAmortizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Francés", "Alemán", "Americano" }));
        entradaSistemaAmortizacion.setToolTipText("");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 204, 0));
        jLabel7.setText("Moneda");
        jLabel7.setToolTipText("");

        entradaTipoMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colones", "Dólares" }));

        botonCalcularAmortizacion.setBackground(new java.awt.Color(153, 153, 153));
        botonCalcularAmortizacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCalcularAmortizacion.setForeground(new java.awt.Color(102, 204, 0));
        botonCalcularAmortizacion.setText("Calcular");
        botonCalcularAmortizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularAmortizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(entradaDeudaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(entradaPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(entradaTasaAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entradaNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(entradaSistemaAmortizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entradaTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(botonCalcularAmortizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaDeudaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaTasaAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaSistemaAmortizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonCalcularAmortizacion)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        entradaNombreCliente.getAccessibleContext().setAccessibleName("entradaNombre");
        entradaDeudaInicial.getAccessibleContext().setAccessibleName("entradaMonto");
        entradaPlazo.getAccessibleContext().setAccessibleName("entradaPlazo");
        entradaTasaAnual.getAccessibleContext().setAccessibleName("entradaTasaInteres");
        entradaSistemaAmortizacion.getAccessibleContext().setAccessibleName("entradaAmortizacion");
        botonCalcularAmortizacion.getAccessibleContext().setAccessibleName("botonCalcular");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularAmortizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularAmortizacionActionPerformed
        // TODO add your handling code here:
        Controlador principal = new Controlador();
        DatosDTO datos  = new DatosDTO();
        String nombreCliente;
        double deudaInicial = 0;
        int plazo = 0;
        double interesAnual = 0;
        String sistemaAmortizacion;
        String moneda;
        boolean validar = true;
        
        //Obtiene valores del cleinte
        nombreCliente = entradaNombreCliente.getText();
        
        //Validacion del Monto Inicial
        try{
            deudaInicial = Double.parseDouble(entradaDeudaInicial.getText());
        }
        catch(Exception e)
        {
            validar = false;
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido para el Monto");
        }
        
        //Validacion Plazo
        try{
            plazo = Integer.parseInt(entradaPlazo.getText());
        }
        catch(Exception e){
            validar = false;
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido para el Plazo");
        }
        
        //Validacion de la tasa de interes
        try{
            interesAnual = Double.parseDouble(entradaTasaAnual.getText());
        }
        catch(Exception e){
            validar = false;
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido para la Tasa de Interés");
        }
        
        sistemaAmortizacion = (String)entradaSistemaAmortizacion.getSelectedItem();
        
        moneda = (String)entradaTipoMoneda.getSelectedItem();

        if(validar==true){
            datos.setDeudaInicial(deudaInicial);
            datos.setInteresAnual(interesAnual);
            datos.setMoneda(moneda);
            datos.setNombreCliente(nombreCliente);
            datos.setPlazo(plazo);
            datos.setSistemaAmortizacion(sistemaAmortizacion);
            principal.consultarAmortizacion(datos);
            JOptionPane.showMessageDialog(null,datos.imprimir());
        }
    }//GEN-LAST:event_botonCalcularAmortizacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcularAmortizacion;
    private javax.swing.JTextField entradaDeudaInicial;
    private javax.swing.JTextField entradaNombreCliente;
    private javax.swing.JTextField entradaPlazo;
    private javax.swing.JComboBox<String> entradaSistemaAmortizacion;
    private javax.swing.JTextField entradaTasaAnual;
    private javax.swing.JComboBox<String> entradaTipoMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
